
spring:
  jackson.deserialization.fail-on-unknown-properties: false
  groovy.template.check-template-location: false

rest.api.version: 1.0

graphite:
  host: graphite.hackathon.dev.4finance.net

metrics.path:
  country: pl
  app: loan-application-service-pl

stubrunner.stubs:
  repository.root: "http://nexus.hackathon.dev.4finance.net/nexus/content/repositories/releases/"
  group: com.ofg
  module: stub-definitions

server:
  port: 8054

stubrunner.use-microservice-definitions: true
stubrunner.skip-local-repo: true
